server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://linux:3306/spike_system?serverTimeZone=GMT+8
    username: root
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  jackson:
#    改成东八区
    time-zone: GMT+8